# Generated by Django 5.2.5 on 2025-08-20 08:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Donor',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='idpic',
            field=models.ImageField(null=True, upload_to='staff'),
        ),
    ]
