# Generated by Django 5.2.5 on 2025-08-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_userprofile_donor_staffprofile_idpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='admin_remark',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='last_update',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='staffremark',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
