# Generated by Django 5.2.5 on 2025-08-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_donation_admin_remark_donation_last_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
