# Generated by Django 5.2.5 on 2025-09-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_location_alter_donation_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
