# Generated by Django 5.2.5 on 2025-09-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_booking_booked_by_alter_booking_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='reached_location',
            field=models.BooleanField(default=False),
        ),
    ]
